table mv_retour_actif_prepaid
	lineageTag: 56781365-d4a3-4cec-a38c-f025c31c909f

	column jour
		dataType: dateTime
		formatString: Long Date
		lineageTag: 49ea78fd-8b43-413a-8de8-0b95f9dc0bb8
		summarizeBy: none
		sourceColumn: jour

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mois_appel
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b12f65b-bbce-48fe-908e-e10131a89de5
		summarizeBy: none
		sourceColumn: mois_appel

		variation Variation
			isDefault
			relationship: 9f41d64b-2aa2-469e-998d-cf7627c32121
			defaultHierarchy: LocalDateTable_ca5c231e-31de-41af-a64c-46341355513d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column campagne
		dataType: string
		lineageTag: 1412a44a-182f-49b0-b791-b465cb429ebc
		summarizeBy: none
		sourceColumn: campagne

		annotation SummarizationSetBy = Automatic

	column nb_contactes
		dataType: int64
		formatString: 0
		lineageTag: 00c445df-cc74-48bc-8d61-19294785a5a0
		summarizeBy: sum
		sourceColumn: nb_contactes

		annotation SummarizationSetBy = Automatic

	column nb_decroches
		dataType: int64
		formatString: 0
		lineageTag: a6d5b360-e4f2-4d9d-b348-ab455c4277a2
		summarizeBy: sum
		sourceColumn: nb_decroches

		annotation SummarizationSetBy = Automatic

	column nb_actifs_au_appel
		dataType: int64
		formatString: 0
		lineageTag: 817cdb80-3bb0-4204-a6aa-1baddba4f5f5
		summarizeBy: sum
		sourceColumn: nb_actifs_au_appel

		annotation SummarizationSetBy = Automatic

	column nb_actifs_aujourdhui
		dataType: int64
		formatString: 0
		lineageTag: 48a92e52-be77-4399-9b30-dcd65c130599
		summarizeBy: sum
		sourceColumn: nb_actifs_aujourdhui

		annotation SummarizationSetBy = Automatic

	column nb_recharges
		dataType: int64
		formatString: 0
		lineageTag: 8f8e495c-03be-48f0-9004-18aba63f4dd3
		summarizeBy: sum
		sourceColumn: nb_recharges

		annotation SummarizationSetBy = Automatic

	column montant_total
		dataType: double
		lineageTag: 72cff1b4-c1de-4a3d-855f-43af8a4fe624
		summarizeBy: sum
		sourceColumn: montant_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nb_decroche_et_recharge
		dataType: int64
		formatString: 0
		lineageTag: 6d275622-d1ee-4dde-8ab1-58b4efde0b59
		summarizeBy: sum
		sourceColumn: nb_decroche_et_recharge

		annotation SummarizationSetBy = Automatic

	column nb_decroche_et_actif
		dataType: int64
		formatString: 0
		lineageTag: adbb7516-55e2-4f2b-a6e3-e4a1c3cd8843
		summarizeBy: sum
		sourceColumn: nb_decroche_et_actif

		annotation SummarizationSetBy = Automatic

	column taux_retour
		dataType: double
		lineageTag: 64b6346d-328a-4a93-94f8-2d212adcab18
		summarizeBy: sum
		sourceColumn: taux_retour

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column taux_decroche
		dataType: double
		lineageTag: 819262fe-620e-48c5-8a71-4af2dc5e9ebc
		summarizeBy: sum
		sourceColumn: taux_decroche

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column taux_actif_au_appel
		dataType: double
		lineageTag: 9f9e5e77-458d-4db9-90fb-ef38745fee37
		summarizeBy: sum
		sourceColumn: taux_actif_au_appel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column taux_actif_aujourdhui
		dataType: double
		lineageTag: 03223a77-b226-4db1-b3ea-bed7ef48d467
		summarizeBy: sum
		sourceColumn: taux_actif_aujourdhui

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition mv_retour_actif_prepaid = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("localhost:5432", "Analyse_perso_churn"), "select * from mv_retour_actif_prepaid ", null, [EnableFolding=true]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"jour", type date}, {"mois_appel", type date}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

